import type { Metadata } from "next";
// import { Inter, Vazirmatn } from "next/font/google";
import "./globals.css";

// const inter = Inter({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const Vazir = Vazirmatn({
//   variable: "--font-Vazirmatn",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next 16",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
// edit the leyout
