import type { Metadata } from "next";
// import { Inter, Vazirmatn } from "next/font/google";
import "./globals.css";

// const inter = Inter({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const Vazir = Vazirmatn({
//   variable: "--font-Vazirmatn",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: {
    default: "protfolio",
    template: "Mohammad | %s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="w-full h-screen bg-gray-700 text-white">{children}</div>
      </body>
    </html>
  );
}
// edit the leyout
