import type { Metadata } from "next";
import { Inter, Vazirmatn } from "next/font/google";
const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const Vazir = Vazirmatn({
  variable: "--font-Vazirmatn",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next 16",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter} ${Vazir} antialiased`}>
        <h1 className="text-center text-4xl p-4">
          This is the nested post page
        </h1>
        {children}
      </body>
    </html>
  );
}
