import type { Metadata } from "next";
// import { Inter, Vazirmatn } from "next/font/google";
import "../globals.css";
// const inter = Inter({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const Vazir = Vazirmatn({
//   variable: "--font-Vazirmatn",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next 16",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiase`}>
        <nav className="w-full p-4 text-white bg-gray-500  flex justify-center">
          <h1 className="text-center font-bold text-4xl">Header</h1>
        </nav>
        {children}
        <footer className="  w-full text-white p-4  bg-gray-500 bottom-0 right-0 absolute">
          <h1 className="text-center font-bold text-4xl ">Footer</h1>
        </footer>
      </body>
    </html>
  );
}
// edit the leyout
